# Generated by Django 5.0.6 on 2024-05-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
