# Generated by Django 5.0.6 on 2024-05-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_todo_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Products',
        ),
    ]
